# Generated by Django 5.2 on 2025-04-07 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200, verbose_name='질문')),
                ('order', models.IntegerField(default=0, verbose_name='질문 순서')),
            ],
            options={
                'verbose_name': '질문',
                'verbose_name_plural': '질문',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='설문조사 제목')),
                ('description', models.TextField(blank=True, verbose_name='설문조사 설명')),
                ('pub_date', models.DateTimeField(verbose_name='게시일')),
            ],
            options={
                'verbose_name': '설문조사',
                'verbose_name_plural': '설문조사',
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200, verbose_name='선택지')),
                ('votes', models.IntegerField(default=0, verbose_name='투표수')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='polls.question', verbose_name='질문')),
            ],
            options={
                'verbose_name': '선택지',
                'verbose_name_plural': '선택지',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='polls.survey', verbose_name='설문조사'),
        ),
    ]
