# Generated by Django 5.2 on 2025-04-07 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('text', '단답형'), ('textarea', '주관식')], default='text', max_length=10, verbose_name='질문 유형'),
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50, verbose_name='닉네임')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='제출일')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='polls.survey', verbose_name='설문조사')),
            ],
            options={
                'verbose_name': '응답',
                'verbose_name_plural': '응답',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(verbose_name='답변')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='polls.question', verbose_name='질문')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='polls.response', verbose_name='응답')),
            ],
            options={
                'verbose_name': '답변',
                'verbose_name_plural': '답변',
            },
        ),
    ]
