# Generated by Django 5.2 on 2025-04-07 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_question_question_type_response_answer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
