# Generated by Django 5.2 on 2025-04-07 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_delete_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('text', '단답형'), ('textarea', '주관식'), ('choice', '객관식')], default='text', max_length=10, verbose_name='질문 유형'),
        ),
        migrations.CreateModel(
            name='QuestionChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200, verbose_name='선택지')),
                ('is_correct', models.BooleanField(default=False, verbose_name='정답 여부')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='polls.question', verbose_name='질문')),
            ],
            options={
                'verbose_name': '객관식 선택지',
                'verbose_name_plural': '객관식 선택지',
            },
        ),
        migrations.AddField(
            model_name='answer',
            name='selected_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.questionchoice', verbose_name='선택한 답변'),
        ),
    ]
